[versions]
agp = "8.8.2"
animation = "1.7.8"
kotlinxCoroutinesTest = "1.10.1"
mapboxnavigation = "3.7.2"
autofill = "2.8.0-rc.1"
cameraLifecycle = "1.4.1"
coilCompose = "3.1.0"
faceDetection = "16.1.7"
generativeai = "0.9.0"
gradle = "8.1.4"
kotlin = "2.0.0"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
kotlinxCoroutinesPlayServices = "1.10.1"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.10.1"
composeBom = "2025.02.00"
litert = "1.2.0"
loggingInterceptor = "4.9.0"
mockkAndroid = "1.13.17"
moshi = "1.12.0"
moshi-kotlin = "1.15.2"
navigationCompose = "2.8.8"
okhttp = "4.9.0"
picovoiceAndroid = "3.0.1"
porcupineAndroid = "3.0.1"
tasksVision = "latest.release"
cameraCore = "1.4.1"
uiTextGoogleFonts = "1.7.8"
playServicesMlkitBarcodeScanning = "18.3.1"
playServicesLocation = "21.3.0"
workRuntimeKtx = "2.10.0"
rules = "1.6.1"
espressoIntents = "3.6.1"
workTesting = "2.10.0"

[libraries]
androidx-animation = { module = "androidx.compose.animation:animation", version.ref = "animation" }
androidx-work-testing = { module = "androidx.work:work-testing", version.ref = "workTesting" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockkAndroid" }
navigationcore = { module = "com.mapbox.navigationcore:android", version.ref = "mapboxnavigation" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraLifecycle" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraLifecycle" }
androidx-camera-mlkit-vision = { module = "androidx.camera:camera-mlkit-vision", version.ref = "cameraLifecycle" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "cameraLifecycle" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
autofill = { module = "com.mapbox.search:autofill", version.ref = "autofill" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }
discover = { module = "com.mapbox.search:discover", version.ref = "autofill" }
face-detection = { module = "com.google.mlkit:face-detection", version.ref = "faceDetection" }
generativeai = { module = "com.google.ai.client.generativeai:generativeai", version.ref = "generativeai" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinxCoroutinesPlayServices" }
litert = { module = "com.google.ai.edge.litert:litert", version.ref = "litert" }
litert-support-api = { group = "com.google.ai.edge.litert", name = "litert-support-api", version.ref = "litert" }
litert-gpu = { group = "com.google.ai.edge.litert", name = "litert-gpu", version.ref = "litert" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
mapbox-search-android = { module = "com.mapbox.search:mapbox-search-android", version.ref = "autofill" }
mapbox-search-android-ui = { module = "com.mapbox.search:mapbox-search-android-ui", version.ref = "autofill" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi-kotlin" }
offline = { module = "com.mapbox.search:offline", version.ref = "autofill" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
picovoice-android = { module = "ai.picovoice:picovoice-android", version.ref = "picovoiceAndroid" }
place-autocomplete = { module = "com.mapbox.search:place-autocomplete", version.ref = "autofill" }
porcupine-android = { module = "ai.picovoice:porcupine-android", version.ref = "porcupineAndroid" }
reorderable = { module = "sh.calvin.reorderable:reorderable", version = "2.4.3" }
tasks-vision = { module = "com.google.mediapipe:tasks-vision", version.ref = "tasksVision" }
androidx-camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "cameraCore" }
androidx-ui-text-google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts", version.ref = "uiTextGoogleFonts" }
play-services-mlkit-barcode-scanning = { group = "com.google.android.gms", name = "play-services-mlkit-barcode-scanning", version.ref = "playServicesMlkitBarcodeScanning" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }
ui-components = { module = "com.mapbox.navigationcore:ui-components", version.ref = "mapboxnavigation" }
androidx-rules = { group = "androidx.test", name = "rules", version.ref = "rules" }
androidx-espresso-intents = { group = "androidx.test.espresso", name = "espresso-intents", version.ref = "espressoIntents" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

